title: Aimee Ukasick
email: aimeeu.opensource@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Open Source Advocate | Tech Writer | Software Developer |
  Collaborating Globally | Bridging Gaps | Spearheading Change |
  Driving Success in an Open Source World

twitter_username: aimee.ukasick
github_username:  aimeeu
linkedin_username: aimee-ukasick

# theme: jekyll-theme-minimal
